Update git hook pre-commit

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,12 +1,19 @@
 #!/bin/sh
 
 # Go linter
-echo "Running golangci-lint..."
-golangci-lint run ./...
-if [ $? -ne 0 ]; then
-  echo "Go linting failed! Commit aborted."
-  exit 1
+
+if find . -name "*.go" | grep -q .; then
+  echo "Go files found, running golangci-lint..."
+  golangci-lint run ./...
+  if [ $? -ne 0 ]; then
+    echo "Go linting failed! Commit aborted."
+    exit 1
+  fi
+else
+  echo "No Go files found, skipping Go lint."
 fi
+
+
 
 # Python flake8
 echo "Running flake8..."
